tmux:
  symbols:
    branch: " "
    ahead: " "
    behind: " "
    staged: " "
    modified: " "
    untracked: " "
    clean: " "

  styles:
    clear: "#[default]"
    state: "#[fg=#f07178,bold]"
    branch: "#[fg=#bfbdb6]"
    remote: "#[fg=#59c2ff]"
    divergence: "#[fg=#ffb454]"
    staged: "#[fg=#aad94c,bold]"
    conflict: "#[fg=#d95757,bold]"
    modified: "#[fg=#73b8ff,bold]"
    untracked: "#[fg=#d2a6ff,bold]"
    stashed: "#[fg=#95e6cb,bold]"
    clean: "#[fg=#70bf56,bold]"
    insertions: "#[fg=#70bf56]"
    deletions: "#[fg=#f26d78]"

  layout: [ branch, remote, " | ", flags ]

  options:
    divergence_space: true
