tmux:
  symbols:
    branch: " "
    ahead: " "
    behind: " "
    staged: " "
    modified: " "
    untracked: " "
    clean: " "

  styles:
    clear: "#[default]"

  layout: [ "#[underscore]", branch, remote, " | ", flags ]

  options:
    divergence_space: true
