tmux:
  symbols:
    branch: " "
    ahead: " "
    behind: " "
    staged: " "
    modified: " "
    untracked: " "
    clean: " "

  styles:
    clear: "#[default,underscore]"

  layout: [ branch, remote, "#[default] | ", flags ]

  options:
    divergence_space: true
