# Volume keys is not used in shortcuts
volume-keys = volume

# Do not capitalize extra keys
extra-keys-text-all-caps = false

# Extra keys layout
extra-keys = [[ \
  {key: ESC, display: 'Esc', popup: ':'}, \
  {key: CTRL, display: 'Ctrl', popup: {key: ALT, display: 'Alt'}}, \
  {key: LEFT, popup: {key: HOME, display: 'Home'}}, \
  {key: DOWN, popup: {key: PGDN, display: 'PgDown'}}, \
  {key: UP, popup: {key: PGUP, display: 'PgUp'}}, \
  {key: RIGHT, popup: {key: END, display: 'End'}}, \
  {key: ALT, display: 'Alt', popup: '/'}, \
  {key: CTRL, display: 'Ctrl', popup: ':'}, \
  {key: TAB, popup: {macro: 'SHIFT TAB'}} \
]]

# Send the Escape key on back.
back-key=escape
