## Options ##

# Prefix
set -g prefix C-a;
unbind C-b;
bind C-a send-prefix

# Focus on events
set -g focus-events on

# Reduce escape delay
set -s escape-time 10

# History limit
set -g history-limit 5000

# Vi-like copy mode
setw -g mode-keys vi

# Proper colors
set -s terminal-features "$TERM:RGB"
set -g default-terminal "tmux-256color"

## Keybindings ##

# Ctrl-Enter and Shift-Enter bindings
bind -n S-Enter send-keys Escape "[13;2u"
bind -n C-Enter send-keys Escape "[13;5u"

# Reload config
bind -n M-r source-file ~/.config/tmux/tmux.conf \; \
            display "Config reloaded!"

# Sessions list sorted by name
bind -n M-s choose-tree -sZ -O name

# Select window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10

# Select panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Resize panes
bind -n M-H resize-pane -L 3
bind -n M-J resize-pane -D 2
bind -n M-K resize-pane -U 2
bind -n M-L resize-pane -R 3

# Split window
bind -n M-C-h split-window -hb
bind -n M-C-j split-window -v
bind -n M-C-k split-window -vb
bind -n M-C-l split-window -h

# Move panes
bind -n M-f swap-pane -D
bind -n M-b swap-pane -U

# Kill panes, windows, sessions
bind -n M-Enter new-window
bind -n M-x kill-pane
bind -n M-q kill-window
bind -n M-Q confirm-before -p "Kill session? (y/n)" kill-session
bind -n M-d detach

# Enter copy mode
bind / copy-mode

# Begin and copy selection
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel \
    "wl-copy || xclip -in -sel clipboard"

# Paste
bind p run "wl-paste || xclip -o -sel clipboard"

## Theme ##

# Start windows and panes numbering from 1
set -g base-index 1
setw -g pane-base-index 1

# Pane borders colors
set -g pane-active-border-style "fg=green"
set -g pane-border-style "fg=black"
set -g pane-border-lines double

# Status and message colors
set -g message-style "bg=black,fg=white"
set -g status-style "bg=black,fg=white"

# Gitmux config path
set -g @GITMUX_CFG "~/.config/gitmux/config.yml"

# Left and right status formats
set -g status-left-length 20
set -g status-left "#[fg=black]#{?client_prefix,#[bg=red],#[bg=yellow]} #S #[bg=default] "
set -g status-right "#(gitmux -cfg #{@GITMUX_CFG} #{pane_current_path})"

# Space between windows
setw -g window-status-separator " "

# Window format
setw -g window-status-current-format "#[fg=black,bg=cyan] #I #W "
setw -g window-status-format "#[fg=cyan,bg=black] #I #W "

## Tpm and plugins ##

# Custom plugins directory
setenv -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.local/share/tmux/plugins"

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-resurrect" 
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin "tmux-plugins/tmux-sessionist"
set -g @plugin "tmux-plugins/tmux-yank"

# Plugins options
set -g @resurrect-capture-pane-contents "on"
set -g @resurrect-dir "~/.local/state/tmux/resurrect"
set -g @continuum-restore "on"
set -g @continuum-save-interval "10"

# TPM local directory and remote repo url
set -g @TPM_DIR "$TMUX_PLUGIN_MANAGER_PATH/tpm"
set -g @TPM_REPO "https://github.com/tmux-plugins/tpm"

# Automatically install TPM if it is not
if "test ! -d #{@TPM_DIR}" \
   "run 'git clone #{@TPM_REPO} #{@TPM_DIR} && \
         #{@TPM_DIR}/bin/install_plugins && \
         echo \"Tpm successfully installed!\""

# Run plugin manager
run "#{@TPM_DIR}/tpm"
