# Ayu Dark colorscheme
# Based on the Ayu colors repo:
# https://github.com/ayu-theme/ayu-colors

# Special
background=#10141c
foreground=#bfbdb6
cursor=#c6c8d1

# Normal colors
color0=#0a0000
color1=#e6495a
color2=#97c142
color3=#e89d37
color4=#17acf2
color5=#c385fe
color6=#84ceb5
color7=#c7c7c7

# Bright colors
color8=#686868
color9=#f07178
color10=#aad94c
color11=#ffb454
color12=#59c2ff
color13=#d2a6ff
color14=#95e6cb
color15=#f6ffff
